# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/garrett/projects/raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/garrett/projects/raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/garrett/projects/raytracer/CMakeFiles /home/garrett/projects/raytracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/garrett/projects/raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytrace

# Build rule for target.
raytrace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytrace
.PHONY : raytrace

# fast build rule for target.
raytrace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/build
.PHONY : raytrace/fast

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

ImagePlane.o: ImagePlane.cpp.o

.PHONY : ImagePlane.o

# target to build an object file
ImagePlane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/ImagePlane.cpp.o
.PHONY : ImagePlane.cpp.o

ImagePlane.i: ImagePlane.cpp.i

.PHONY : ImagePlane.i

# target to preprocess a source file
ImagePlane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/ImagePlane.cpp.i
.PHONY : ImagePlane.cpp.i

ImagePlane.s: ImagePlane.cpp.s

.PHONY : ImagePlane.s

# target to generate assembly for a file
ImagePlane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/ImagePlane.cpp.s
.PHONY : ImagePlane.cpp.s

Plane.o: Plane.cpp.o

.PHONY : Plane.o

# target to build an object file
Plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Plane.cpp.o
.PHONY : Plane.cpp.o

Plane.i: Plane.cpp.i

.PHONY : Plane.i

# target to preprocess a source file
Plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Plane.cpp.i
.PHONY : Plane.cpp.i

Plane.s: Plane.cpp.s

.PHONY : Plane.s

# target to generate assembly for a file
Plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Plane.cpp.s
.PHONY : Plane.cpp.s

Ray.o: Ray.cpp.o

.PHONY : Ray.o

# target to build an object file
Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Ray.cpp.o
.PHONY : Ray.cpp.o

Ray.i: Ray.cpp.i

.PHONY : Ray.i

# target to preprocess a source file
Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Ray.cpp.i
.PHONY : Ray.cpp.i

Ray.s: Ray.cpp.s

.PHONY : Ray.s

# target to generate assembly for a file
Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Ray.cpp.s
.PHONY : Ray.cpp.s

SceneObject.o: SceneObject.cpp.o

.PHONY : SceneObject.o

# target to build an object file
SceneObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/SceneObject.cpp.o
.PHONY : SceneObject.cpp.o

SceneObject.i: SceneObject.cpp.i

.PHONY : SceneObject.i

# target to preprocess a source file
SceneObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/SceneObject.cpp.i
.PHONY : SceneObject.cpp.i

SceneObject.s: SceneObject.cpp.s

.PHONY : SceneObject.s

# target to generate assembly for a file
SceneObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/SceneObject.cpp.s
.PHONY : SceneObject.cpp.s

Sphere.o: Sphere.cpp.o

.PHONY : Sphere.o

# target to build an object file
Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Sphere.cpp.o
.PHONY : Sphere.cpp.o

Sphere.i: Sphere.cpp.i

.PHONY : Sphere.i

# target to preprocess a source file
Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Sphere.cpp.i
.PHONY : Sphere.cpp.i

Sphere.s: Sphere.cpp.s

.PHONY : Sphere.s

# target to generate assembly for a file
Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/Sphere.cpp.s
.PHONY : Sphere.cpp.s

raytrace.o: raytrace.cpp.o

.PHONY : raytrace.o

# target to build an object file
raytrace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/raytrace.cpp.o
.PHONY : raytrace.cpp.o

raytrace.i: raytrace.cpp.i

.PHONY : raytrace.i

# target to preprocess a source file
raytrace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/raytrace.cpp.i
.PHONY : raytrace.cpp.i

raytrace.s: raytrace.cpp.s

.PHONY : raytrace.s

# target to generate assembly for a file
raytrace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/raytrace.cpp.s
.PHONY : raytrace.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raytrace"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... ImagePlane.o"
	@echo "... ImagePlane.i"
	@echo "... ImagePlane.s"
	@echo "... Plane.o"
	@echo "... Plane.i"
	@echo "... Plane.s"
	@echo "... Ray.o"
	@echo "... Ray.i"
	@echo "... Ray.s"
	@echo "... SceneObject.o"
	@echo "... SceneObject.i"
	@echo "... SceneObject.s"
	@echo "... Sphere.o"
	@echo "... Sphere.i"
	@echo "... Sphere.s"
	@echo "... raytrace.o"
	@echo "... raytrace.i"
	@echo "... raytrace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

